version: "3.9"

services:
  # Nvidia
  init:
    profiles:
      - init
    build:
      context: .
      dockerfile: docker/nvidia/Dockerfile
    tty: true
    network_mode: "host"
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
    volumes:
      - type: bind
        source: .
        target: /workspace
    command: [ "init" ]

  reinstall:
    profiles:
      - reinstall
    build:
      context: .
      dockerfile: docker/nvidia/Dockerfile
    tty: true
    network_mode: "host"
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
    volumes:
      - type: bind
        source: .
        target: /workspace
    command: [ "reinstall" ]

  web:
    profiles:
      - web
    build:
      context: .
      dockerfile: docker/nvidia/Dockerfile
    network_mode: "host"
    tty: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
    volumes:
      - type: bind
        source: .
        target: /workspace

  # ROCm
  init2:
    profiles:
      - init2
    build:
      context: .
      dockerfile: docker/rocm/Dockerfile
    tty: true
    network_mode: "host"
    ipc: host
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    group_add:
      - video
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: bind
        source: .
        target: /workspace
    command: [ "init" ]

  reinstall2:
    profiles:
      - reinstall2
    build:
      context: .
      dockerfile: docker/rocm/Dockerfile
    tty: true
    network_mode: "host"
    ipc: host
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    group_add:
      - video
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: bind
        source: .
        target: /workspace
    command: [ "reinstall" ]

  web2:
    profiles:
      - web2
    build:
      context: .
      dockerfile: docker/rocm/Dockerfile
    network_mode: "host"
    tty: true
    ipc: host
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    group_add:
      - video
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: bind
        source: .
        target: /workspace