version: "3.9"

services:
  init:
    profiles:
      - init
    build:
      context: .
      dockerfile: docker/rocm/Dockerfile
    tty: true
    network_mode: "host"
    ipc: host
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    group_add:
      - video
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: bind
        source: .
        target: /workspace
    command: [ "init" ]

  reinstall:
    profiles:
      - reinstall
    build:
      context: .
      dockerfile: docker/rocm/Dockerfile
    tty: true
    network_mode: "host"
    ipc: host
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    group_add:
      - video
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: bind
        source: .
        target: /workspace
    command: [ "reinstall" ]

  web:
    build:
      context: .
      dockerfile: docker/rocm/Dockerfile
    network_mode: "host"
    tty: true
    ipc: host
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    group_add:
      - video
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: bind
        source: .
        target: /workspace

  jupyter:
    image: jupyter/minimal-notebook:latest
    ports:
      - "8888:4545"
    volumes:
      - type: bind
        source: .
        target: /workspace
