version: "3.9"

services:
  init:
    profiles:
      - init
    build:
      context: docker/nvidia/
      dockerfile: docker/nvidia/Dockerfile
    tty: true
    network_mode: "host"
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
    volumes:
      - type: bind
        source: .
        target: /workspace
    command: [ "init" ]

  reinstall:
    profiles:
      - reinstall
    build:
      context: docker/nvidia/
      dockerfile: docker/nvidia/Dockerfile
    tty: true
    network_mode: "host"
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
    volumes:
      - type: bind
        source: .
        target: /workspace
    command: [ "reinstall" ]

  web:
    build:
      context: docker/nvidia/
      dockerfile: docker/nvidia/Dockerfile
    network_mode: "host"
    tty: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
    volumes:
      - type: bind
        source: .
        target: /workspace
  
  jupyter:
    image: jupyter/minimal-notebook:latest
    ports:
      - "4545:8888"
    volumes:
      - type: bind
        source: .
        target: /workspace