version: "3.9"

services:
  reinstall:
    profiles:
      - reinstall
    build:
      context: .
    tty: true
    network_mode: "host"
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
    volumes:
      - type: bind
        source: .
        target: /workspace
    command: [ "reinstall" ]

  web:
    build:
      context: .
    network_mode: "host"
    tty: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
    volumes:
      - type: bind
        source: .
        target: /workspace
  
  jupyter:
    image: jupyter/minimal-notebook:latest
    ports:
      - "127.0.0.1:8888:8888"
    command:
      - start-notebook.sh
      - --NotebookApp.token=''
      - --NotebookApp.disable_check_xsrf=True
    volumes:
      - type: bind
        source: .
        target: /home/jovyan/work